### ISSUE TITLE
raycast / raycast_query crash when length of raycast is 0

### ISSUE THREAD

**Issue by 8bitskull** [selimanac/DAABBCC#9]
Noticed this when I was doing a raycast for a moving object. For some reason some of my frames had a dt of 0, meaning I would check the same starting and end position.

`Assertion failed: r.LengthSquared() > 0.0f, file upload/daabbcc/include/DynamicTree/b2DynamicTree.h, line 209`

**Comment by selimanac** [comment]
This is not an error. Raycast length must be bigger then 0.0f. And this assertion comes from [Box2D lib](https://github.com/erincatto/box2d/blob/23c5d60668dc84e731e1f700188df4e3aaa9b5f6/include/box2d/b2_dynamic_tree.h#L228). So you'll get this result on every un-modifield Box2D. Even  [Defold](https://github.com/defold/defold/blob/1ae302ec33d4514408c04ad3ae5d3c1efe2057bd/engine/physics/src/box2d/Box2D/Collision/b2DynamicTree.h#L232) has this. 
All I can do is to prevent crash by returning a warning if length i <= 0 , is this ok for you? Also you can check this on Lua too

**Comment by 8bitskull** [comment]
That makes sense! Thanks for explaining.

I'm no expert on how to design this stuff, but it seems reasonable to return no hits and display a warning. Perhaps better than a full crash.

**Comment by selimanac** [comment]
Length check added
